### ISSUE TITLE
Subscribe to the result of an existing label task

### ISSUE THREAD

**Issue by ismail9001** [rickymohk/SwiftTaskQueue#1]
Is it possible to add this functionality?

When creating a task, we specify its label, but as I understand it, we cannot refer to the tasks in the queue.

**Comment by rickymohk** [comment]
Currently the label is purely for debug purpose and has no functionalities. You can obtain the result of a task using the `dispatch<T>(label:block:) async throws -> T` variant. 

If you want to have a subscription functionality, do you mean you want to have multiple consumers of the same task? Could you provide some example code to illustrate how you expect this function to behave?

**Comment by ismail9001** [comment]
```
    func download(_ fileId: String, showProgress: Bool) async throws -> URL {
        if let downloadingTask = downloadingTasks[fileId] {
            let result = await downloadingTask.task.result
            return try result.get()
        } else {
            let downloadTask = Task { () -> URL in
                let localSavedURL = try await coordinator.addRequest(fileId)
                return localSavedURL
            }
            downloadingTasks[fileId] = DownloadTask(task: downloadTask)
            let result = await downloadTask.result
            return try result.get()
        }
    }
```

for example, if we need to save a large file that can be used in various services, then we could create a download task, or if the process is already running, subscribe to the download completion event to get the result in those functions that are waiting to receive it.

In this example downloadingTasks is some dictionary that contain already running unique downloads

**Comment by rickymohk** [comment]
In such case I don't think referencing labeled task from the `taskQueue` is necessary. You can save the `Task` which you spawned to make the async calls to `taskQueue`. Then later retrieve the [value](https://developer.apple.com/documentation/swift/task/value-60t02) of that `Task` unlimited times.
```swift
  var rememberTasks : [String : Task<String?,Error>] = [:]
  let taskId = "..."
  rememberTasks[taskId] = Task{
      return try await taskQueue.dispatch {
          // your async code here
          // ...
          return "result"
      }
  }
  
  //Somewhere else
  let rememberedResult = try? await rememberTasks[taskId]?.value
```
